# Generated by Django 5.1.2 on 2024-10-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendos',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Arriendos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.IntegerField()),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=10)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol_Usuario',
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=225)),
                ('estado_suscripcion', models.CharField(choices=[('activa', 'Activa'), ('desactiva', 'Desactiva')], max_length=10)),
            ],
            options={
                'db_table': 'Tiendas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=225)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleArriendo',
            fields=[
                ('id_detallea', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.arriendos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.inventario')),
            ],
            options={
                'db_table': 'Detalle_Arriendo',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_sub', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
            ],
            options={
                'db_table': 'Suscripcion',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas'),
        ),
        migrations.AddField(
            model_name='arriendos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios'),
        ),
        migrations.CreateModel(
            name='UsuarioTienda',
            fields=[
                ('id_usuario_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.rolusuario')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.tiendas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
            ],
            options={
                'db_table': 'Usuario_Tienda',
            },
        ),
        migrations.AddField(
            model_name='arriendos',
            name='id_usuario_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuariotienda'),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuarios')),
                ('id_usuario_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.usuariotienda')),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_detallev', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.inventario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allsnow_app.ventas')),
            ],
            options={
                'db_table': 'Detalles_Venta',
            },
        ),
    ]
