# Generated by Django 3.1 on 2024-11-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsnow_app', '0004_inventario_nombre_producto_inventario_talla_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'registrarme',
            },
        ),
        migrations.CreateModel(
            name='SolicitudLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'solicitud_local',
            },
        ),
        migrations.DeleteModel(
            name='SolicitudTienda',
        ),
        migrations.RemoveField(
            model_name='solicitudusuario',
            name='conf_contraseña',
        ),
        migrations.RemoveField(
            model_name='solicitudusuario',
            name='conf_correo',
        ),
        migrations.AddField(
            model_name='tiendas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='solicitudusuario',
            table='solicitud_usuario',
        ),
    ]
